---
name: maxskitter-extensions
---
Page:
  extensions:
    - Silvermax\MaxSkitter\Extensions\MaxSkitterDecorator
    - Silvermax\MaxSkitter\Extensions\MaxSkitterConfigExtension

PageController:
  extensions:
    - Silvermax\MaxSkitter\Extensions\MaxSkitterExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Silvermax\MaxSkitter\Extensions\MaxSkitterConfigExtension

SilverStripe\Assets\Image:
  extensions:
    - Silvermax\MaxSkitter\Extensions\MaxSkitterImageDecorator

---
name: maxskitter-defaults
---

Silvermax\MaxSkitter\Extensions\MaxSkitterImageDecorator:
  slideWidth: 800
  slideHeight: 300